// Package preset provides the built-in balanced reference data set:
// 10 parts x 3 operators x 3 trials = 90 readings.
//
// The readings are generated by an exactly-additive scheme so the
// sums of squares have closed, hand-verifiable forms:
//
//	x_ijk = 100 + a_i + b_j + d_k
//
// with (sums and sums of squares shown for hand audit)
//
//	a = [-9,-7,-5,-3,-1,1,3,5,7,9],  sum a = 0,  sum a^2 = 330
//	b = [-1,0,1],                     sum b = 0,  sum b^2 = 2
//	d = [-2,0,2],                     sum d = 0,  sum d^2 = 8
//
// O*R = 9 repeats per part total, P*R = 30 per operator, P*O = 30
// cells for the trial term. All cross terms vanish (every factor is
// centered), hence:
//
//	SS_part   = 9  * 330 = 2970   (df 9)
//	SS_op     = 30 * 2   = 60     (df 2)
//	SS_inter  = 0                 (df 18)
//	SS_repeat = 30 * 8   = 240    (df 60)
//	SS_total  = 3270              (df 89)
//
// The zero interaction (p = 1) triggers the AIAG pooling rule, which is
// exercised by the regression tests as well.
package preset

// Reading is one preset measurement in label space.
type Reading struct {
	Part     string
	Operator string
	Trial    int
	Value    float64
}

var partEffects = []float64{-9, -7, -5, -3, -1, 1, 3, 5, 7, 9}
var opEffects = []float64{-1, 0, 1}
var trialEffects = []float64{-2, 0, 2}

// Hand-calculated ANOVA quantities (see package doc).
const (
	SSPart        = 2970.0
	SSOperator    = 60.0
	SSInteraction = 0.0
	SSRepeat      = 240.0
	SSTotal       = 3270.0

	DFPart   = 9
	DFOp     = 2
	DFInter  = 18
	DFRepeat = 60
	DFTotal  = 89

	PartsCount = 10
	OpCount    = 3
	TrialCount = 3
	N          = 90
	GrandMean  = 100.0
)

// OperatorLabels lists the operator labels in canonical order.
var OperatorLabels = []string{"Alice", "Bob", "Carol"}

// PartLabels lists the part labels in canonical order.
var PartLabels = func() []string {
	out := make([]string, 10)
	for i := range out {
		out[i] = "P" + pad(i+1)
	}
	return out
}()

func pad(n int) string {
	if n < 10 {
		return "0" + string(rune('0'+n))
	}
	return string(rune('0'+n/10)) + string(rune('0'+n%10))
}

// Dataset returns the 90 preset readings, ordered part/operator/trial.
func Dataset() []Reading {
	out := make([]Reading, 0, N)
	for i, a := range partEffects {
		for j, b := range opEffects {
			for k, d := range trialEffects {
				out = append(out, Reading{
					Part:     PartLabels[i],
					Operator: OperatorLabels[j],
					Trial:    k + 1,
					Value:    100 + a + b + d,
				})
			}
		}
	}
	return out
}
